---
# tasks file for mariadb
- name: Open port 3306
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3306
    ctstate: NEW
    syn: match
    jump: ACCEPT
  notify: 
    - save iptables
    - restart iptables

- name: Install MariaDB packages
  yum: name={{ item }} state=present
  with_items:
    - mariadb-server
    - MySQL-python
- name: Ensure MariaDB is running
  service:
    name: mariadb
    state: started

- name: Create DB for WordPress
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    state: present

- name: Create DB user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    host: "{{ app_host }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    state: present
