# -*- mode: ruby -*-
# nvim: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "centos7-virtualbox"

  config.ssh.username = 'packer'
  config.ssh.insert_key = false
  config.ssh.keys_only = false

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  config.vm.provision "ansible" do |ansible|

    ansible.playbook = "../ansible/playbook.yml"

    ansible.extra_vars = {

      "networks" => [{
        "name" => "wan",
        "type" => "public",
        "ipv4" => "192.168.0.0",
        "prefix"  => "24",

        "forward_from" => [
          { "src_network" => "dmz", "src_addr" => "network", "src_port" => "any", "dest_addr" => "any", "dest_port" => "80"},
          { "src_network" => "dmz", "src_addr" => "network", "src_port" => "any", "dest_addr" => "any", "dest_port" => "443"},
          { "src_network" => "dmz", "src_addr" => "network", "src_port" => "any", "dest_addr" => "any", "dest_port" => "25"},
          { "src_network" => "dmz", "src_addr" => "network", "src_port" => "any", "dest_addr" => "any", "dest_port" => "587"},
          { "src_network" => "dmz", "src_addr" => "network", "src_port" => "any", "dest_addr" => "any", "dest_port" => "995"},
        ]
      },
      {
        "name" => "dmz",
        "type" => "private",
        "ipv4" => "192.168.2.0",
        "prefix"  => "24",

        "forward_from" => [
          { "src_network" => "wan", "src_addr" => "any", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "80"},
          { "src_network" => "wan", "src_addr" => "any", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "443"},
          { "src_network" => "wan", "src_addr" => "any", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "25"},
          { "src_network" => "wan", "src_addr" => "any", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "587"},
          { "src_network" => "wan", "src_addr" => "any", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "995"},

          { "src_network" => "lan", "src_addr" => "network", "src_port" => "any", "dest_addr" => "network", "dest_port" => "80"},
          { "src_network" => "lan", "src_addr" => "network", "src_port" => "any", "dest_addr" => "network", "dest_port" => "443"},
          { "src_network" => "lan", "src_addr" => "network", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "25"},
          { "src_network" => "lan", "src_addr" => "network", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "587"},
          { "src_network" => "lan", "src_addr" => "network", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "995"},
          { "src_network" => "lan", "src_addr" => "192.168.3.11", "src_port" => "any", "dest_addr" => "192.168.2.11", "dest_port" => "3306"}
        ]
      },

      {
        "name" => "lan",
        "type" => "private",
        "ipv4" => "192.168.3.0",
        "prefix"  => "24",
      }],

      "dnat_tcp" => {
        "25"  => "192.168.2.11", # SMTP
        "80"  => "192.168.2.11", # HTTP
        "443" => "192.168.2.11", # HTTPS
        "587" => "192.168.2.11", # SMTP
        "995" => "192.168.2.11"  # POP3s
      },
    }
  end

  # Firewall
  config.vm.define "firewall" do |firewall|
    firewall.vm.hostname = "test-firewall.dev"
    #firewall.vm.cloud_init content_type: "text/cloud-config", path: "../terraform/firewall.cfg"
    firewall.vm.network "public_network", ip: "192.168.0.101"  # WAN: Bridge

    firewall.vm.network "private_network", ip: "192.168.2.1",  # DMZ: Internal Network
      virtualbox__intnet: "dmz"
    firewall.vm.network "private_network", ip: "192.168.3.1",  # LAN: Internal Network
      virtualbox__intnet: "lan"
  end

  config.vm.define "app" do |app|
    app.vm.hostname = "test-app.dev"
    #firewall.vm.cloud_init content_type: "text/cloud-config", path: "../terraform/firewall.cfg"
    app.vm.network "private_network", ip: "192.168.2.11", netmask: "255.255.255.0",  # DMZ
      virtualbox__intnet: "dmz"

    $add_routes = <<-'SCRIPT'
      sudo ip route add 192.168.0.0/24 via 192.168.2.1 dev enp0s8
      sudo ip route add 192.168.2.0/24 via 192.168.2.1 dev enp0s8
      sudo ip route add 192.168.3.0/24 via 192.168.2.1 dev enp0s8
    SCRIPT

    app.vm.provision "shell",
      inline: $add_routes
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "test-db.dev"
    #firewall.vm.cloud_init content_type: "text/cloud-config", path: "../terraform/firewall.cfg"
    db.vm.network "private_network", ip: "192.168.3.11", netmask: "255.255.255.0",  # LAN
      virtualbox__intnet: "lan"

    $add_routes = <<-'SCRIPT'
      sudo ip route add 192.168.0.0/24 via 192.168.3.1 dev enp0s8
      sudo ip route add 192.168.2.0/24 via 192.168.3.1 dev enp0s8
      sudo ip route add 192.168.3.0/24 via 192.168.3.1 dev enp0s8
    SCRIPT

    db.vm.provision "shell",
      inline: $add_routes
  end
end
