---
# tasks file for httpd
- block:

  - name: Daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Install apache packages
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Ensure httpd is running
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Open HTTP and HTTPS ports
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: '{{ item }}'
      ctstate: NEW
      syn: match
      jump: ACCEPT
    with_items: [ 80, 443 ]
    notify: 
      - save iptables
      - restart iptables
