---
# tasks file for httpd
- block:

  - name: Daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Install apache packages
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Ensure httpd is running
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Open HTTP and HTTPS ports
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: '{{ item }}'
      ctstate: NEW
      syn: match
      jump: ACCEPT
    with_items: [ 80, 443 ]
    notify: 
      - save iptables
      - restart iptables

  - name: Install PHP Remi Repository
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      update_cache: yes
      state: latest

  - name: Install PHP
    yum: name={{ item }} state=latest enablerepo="remi,remi-php80"
    with_items:
      - php
      - php-mysql
      - php-gd
    notify: restart apache

  - name: Create HOST directory
    file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: packer
      group: packer
      mode: '0755'

  tags:
    - setup apache

- block:
  - name: Set Apache VirtualHost
    template:
      src: "httpd.conf.j2"
      dest: "/etc/httpd/conf.d/{{ http_conf }}"
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Set an apache user for administration folder
    command: htpasswd -cb /etc/httpd/.htpasswd {{ wp_user }} {{ wp_password }}

  - name: Download and unpack latest WordPress
    unarchive:
      src: http://wordpress.org/latest.tar.gz
      dest: "/var/www/{{ http_host }}"
      remote_src: yes
      creates: "/var/www/{{ http_host }}/wordpress"

  - name: Copy WordPress sample config file
    command: mv /var/www/{{ http_host }}/wordpress/wp-config-sample.php /var/www/{{ http_host }}/wordpress/wp-config.php creates=/var/www/{{ http_host }}/wordpress/wp-config.php
    notify: restart apache

  - name: Update WordPress config file with database
    lineinfile:
      path: "/var/www/{{ http_host }}/wordpress/wp-config.php"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{db_name}}' );"}
      - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{db_user}}' );"}
      - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{db_password}}' );"}
      - {'regexp': "define\\( 'DB_HOST', '(.)+' \\);", 'line': "define( 'DB_HOST', '{{db_host}}' );"}
    notify: restart apache

  tags:
    - setup wordpress

- block:

  - name: Enable SELinux
    selinux:
      policy: targeted
      state: enforcing

  - name: Httpd can connect db
    command: setsebool -P httpd_can_network_connect_db 1
    notify: restart apache

  - name: Httpd can network connect
    command: setsebool -P httpd_can_network_connect 1
    notify: restart apache

  tags:
    - selinux conf
