---
- name: Collect data
  hosts: all
  gather_facts: yes

- hosts: firewall
  roles:
    - name: firewall
      become: yes

    - name: vpn
      become: yes

- hosts: databases
  roles:
    - name: mariadb
      become: yes

- hosts: webservers
  roles:
    - name: httpd
      become: yes

- hosts: loadbalancing
  roles:
    - name: failover
      become: yes
