---
- name: Collect data
  hosts: all
  gather_facts: yes

- hosts: firewall
  roles:
    - name: firewall
      become: yes
      tags:
        - firewall
        - never
    - name: vpn
      become: yes
      tags:
        - never

- hosts: loadbalancing
  roles:
    - name: failover
      become: yes
      tags:
        - never

- hosts: webservers
  roles:
    - name: httpd
      become: yes
      tags:
        - never

- hosts: databases
  roles:
    - name: mariadb
      become: yes
      tags:
        - testing
