---
- name: "Setup.yml"
  hosts: all
  gather_facts: yes

  vars_files:
    - vars.yml

  roles: 
    - role: '../../ansible/roles/iptables'
      become: yes

  pre_tasks:
  - name: Install epel repo (RedHat)
    yum:
      name: "epel-release"
      state: latest
    when: ansible_os_family == "RedHat"
    become: yes

  - name: Upgrade all packages (RedHat)
    yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    become: yes

  - name: Install packages (RedHat)
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - net-tools
      - ccze
      - curl
      - git
      - rsync
      - screen
      - tcpdump
      - vim
      - wget
      - cloud-init
      - python-pip
    when: ansible_os_family == "RedHat"
    become: yes

  - name: Install vmware cloud-init
    shell:
      cmd: curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh -
    become: yes

  - name: Install open-vm-tools (RedHat)
    yum:
      name: open-vm-tools
      state: latest
    when: 
      - ansible_os_family == "RedHat"
      - ansible_virtualization_type == "VMware"
    become: yes

  post_tasks:
  - name: Create vim configuration file
    file:
      path: /root/.vimrc
      state: touch
      owner: root
      group: root
      mode: 0644
    become: yes

  - name: Configure vim
    blockinfile:
      path: /root/.vimrc
      block: |
        set nocompatible
        set number
        set autoindent
        set tabstop=4
        set shiftwidth=4
        set expandtab
        syntax on
        highlight Comment ctermfg=LightCyan
      marker: ""
      state: present
    become: yes
  - name: Generate RSA host key
    command:
      cmd: ssh-keygen -q -t rsa -f ~/.ssh/id_rsa -C "" -N {{ key_pass }}
      creates: ~/.ssh/id_rsa
    delegate_to: 127.0.0.1
    tags:
      - pubkey

  - name: Create .ssh directory
    file:
      path: "~/.ssh"
      state: directory
      owner: packer
      group: packer
      mode: '0700'
    tags:
      - pubkey

  - name: Save pubkey
    template:
      src: "~/.ssh/id_rsa.pub"
      dest: "~/.ssh/authorized_keys"
      mode: '0600'
    tags:
      - pubkey

  - name: Disable UseDNS
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^UseDNS"
      line: "UseDNS no"
      state: present
    become: yes

  - name: Disable GSSAPIAuthentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication no"
      state: present
    become: yes
